defaut:
	python3 lab2.py

1-persistent:
	python3 lab2.py -A 7
	python3 lab2.py -A 10
	python3 lab2.py -A 20

non-persistent:
	python3 lab2.py -P -A 7
	python3 lab2.py -P -A 10
	python3 lab2.py -P -A 20
